FROM eclipse-temurin:17-jdk

WORKDIR /app

# install dependency
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

# download Metabase jar
RUN wget -q https://downloads.metabase.com/v0.49.9/metabase.jar

# plugins
RUN mkdir -p /plugins && \
    wget -q -O /plugins/duckdb.metabase-driver.jar \
    "https://github.com/motherduckdb/metabase_duckdb_driver/releases/download/1.5.2.0/duckdb.metabase-driver.jar"

ENV MB_PLUGINS_DIR=/plugins

EXPOSE 3000

CMD ["java", "-jar", "metabase.jar"]